import "dotenv/config";

import express, { json, urlencoded } from "express";
import cors from "cors";
const app = express();
const PORT = process.env.PORT || 8080;
import fileUpload from "express-fileupload";

import main from "./router/mainRoute.js";
import setting from "./router/settingRoute.js";
import student from "./router/studentRoute.js";
import download from "./router/downloadRoute.js";
import codeMaster from "./router/codeMasterRoute.js";
import campus from "./router/campusRoute.js";
import institute from "./router/instituteRoute.js";
import course from "./router/courseRoute.js";
import user from "./router/auth/userRoute.js";
import employee from "./router/employeeRoute.js";
import teacher from "./router/teacherMappingRoute.js";
import libraryCreation from "./router/libraryCreationRoute.js";
import libraryItem from "./router/libraryAddItemRoutes.js";
import timeTable from "./router/timeTableRoute.js";
import faculityLoad from "./router/faculityLoadRoute.js";
import timeTableCreate from "./router/timeTableCreateRoute.js";
import libraryMember from "./router/libraryMemberRoute.js";
import attendance from "./router/attendanceRoute.js";
import classRoom from "./router/classRoomRoute.js";
import feeGroup from "./router/feeGroupRoute.js";
import feeType from "./router/feeTypeRoute.js";
import feeInvoice from "./router/feeInvoiceRoute.js";
import feeInvoiceDetails from "./router/feeInvoiceDetailRoute.js";
import role from "./router/roleRoute.js";
import permission from "./router/permissionRoute.js";
import rolePermissionMapping from "./router/rolePermissionMappingRoute.js";
import userRolePermission from "./router/userRolePermissionRoute.js";
import dormitoryRoomType from "./router/roomTypeRoute.js";
import dormitoryList from "./router/dormitoryListRoute.js";
import addDormitory from "./router/addDormitoryRoute.js";
import examType from "./router/examTypeRoute.js";
import examSetup from "./router/examSetupRoute.js";
import examAttendance from "./router/examAttendanceRoute.js";
import transportRoute from "./router/transportRoute.js";
import vehicleRoute from "./router/vehicleRoute.js";
import assignVehicleRoute from "./router/assignVehicleRoute.js";
import acedmicYear from "./router/acedmicYearRoute.js";
import section from "./router/sectionRoute.js";
import holiday from "./router/holidayRoute.js";
import electiveSubject from "./router/electiveSubjectRoute.js";
import building from "./router/buildingRoute.js";
import floor from "./router/floorRoute.js";
import head from "./router/headRoute.js";
import subAccount from "./router/subAccountRoute.js"; // this is department
import department from "./router/departmentRoute.js"; // this is sub_account
import staff from "./router/staffRoute.js";
import departmentStructure from "./router/departmentStructureRoute.js";
import syllabus from "./router/syllabusRoute.js";
import session from "./router/sessionRoute.js";
import po from "./router/poRoute.js";
import co from "./router/coRoute.js";
import feePlan from "./router/feePlanRoute.js";
import feeInvoiceRecord from "./router/feeInvoiceDetailRecordRoute.js";
import studentInvoice from "./router/studentInvoiceRoute.js";
import lesson from "./router/lessonRoute.js";
import notice from "./router/noticeRoute.js";
import examStructure from "./router/examStructureRoute.js";
import schedule from "./router/scheduleRoute.js";
import leavePolicy from "./router/leavePolicyRouter.js";
import leaveRequest from "./router/leaveRequestRouter.js";
import leaveBalance from "./router/leaveBalanceRouter.js";
import examScheduleMapping from "./router/examStructureScheduleMappingRoute.js";
import libraryStructure from "./router/libraryStructureRoute.js";
import internalAssessment from "./router/internalAssessmentRoute.js";
import jobSetting from "./router/jobSettingsRoutes.js";
import jobs from "./router/jobRoutes.js";
import grade from "./router/gradeRoute.js";
import credit from "./router/creditRoute.js";
import evalution from "./router/evalutionRoute.js";
import terms from "./router/termsRoute.js";
import subjects from "./router/subjectRoute.js";
import userPermission from "./router/userPermissionRoute.js";
import resultStudent from "./router/resultStudentRoutes.js";
import questionPaper from "./router/questionPaperRoute.js";
import questionBank from "./router/questionBankRoute.js";
import classSection from "./router/classSectionRoute.js";
import teacherExamAssignment from "./router/teacherExamAssignmentRoute.js";
import questionPaperBlueprint from "./router/questionPaperBlueprintRoute.js";
import examSetupTypeTerm from "./router/examSetupTypeTermRoute.js";
import examSetupType from "./router/examSetupTypeRoute.js";
import examSchedule from "./router/examScheduleRoute.js";
import options from "./router/optionsRoute.js";
import subjectWeightage from "./router/subjectWeightageRoute.js";
import examRoomCapacity from "./router/examRoomCapacityRoute.js";


// middleware
app.use(fileUpload());
app.use(json());
app.use(cors());
app.use(urlencoded({ extended: true }));

//routes

app.use("/campus", campus);
app.use("/institute", institute);
app.use("/course", course);
app.use("/session", session);
app.use("/subject", subjects);
app.use("/terms", terms);
app.use("/syllabus", syllabus);
app.use("/authorization", userPermission);
app.use("/resultStudent", resultStudent);
app.use("/questionPaper", questionPaper);
app.use("/questionBank", questionBank);
app.use("/classSections", classSection);
app.use("/attendance", attendance);
app.use("/teacherExamAssignment", teacherExamAssignment);
app.use("/questionPaperBlueprint", questionPaperBlueprint);
app.use("/examSetupTypeTerm", examSetupTypeTerm);
app.use("/examSetupType", examSetupType);
app.use("/examSchedule", examSchedule);
app.use("/options", options);
app.use("/subjectWeightage", subjectWeightage);
app.use("/examRoomCapacity", examRoomCapacity);


app.use("/main", main);
app.use("/setting", setting);
app.use("/student", student);
app.use("/download", download);
app.use("/codeMaster", codeMaster);
app.use("/user", user);
app.use("/employee", employee);
app.use("/teacher", teacher);
app.use("/libraryCreation", libraryCreation);
app.use("/libraryItem", libraryItem);
app.use("/timeTable", timeTable);
app.use("/faculityLoad", faculityLoad);
app.use("/timeTableCreate", timeTableCreate);
app.use("/libraryMember", libraryMember);
app.use("/classRoom", classRoom);
app.use("/feeGroup", feeGroup);
app.use("/feeType", feeType);
app.use("/feeInvoice", feeInvoice);
app.use("/feeInvoiceDetails", feeInvoiceDetails);
app.use("/role", role);
app.use("/permission", permission);
app.use("/rolePermissionMapping", rolePermissionMapping);
app.use("/userRolePermission", userRolePermission);
app.use("/dormitoryRoomType", dormitoryRoomType);
app.use("/dormitoryList", dormitoryList);
app.use("/addDormitory", addDormitory);
app.use("/examType", examType);
app.use("/examSetup", examSetup);
app.use("/examAttendance", examAttendance);
app.use("/transportRoute", transportRoute);
app.use("/vehicle", vehicleRoute);
app.use("/assignVehicle", assignVehicleRoute);
app.use("/acedmicYear", acedmicYear);
app.use("/section", section);
app.use("/holiday", holiday);
app.use("/electiveSubject", electiveSubject);
app.use("/building", building);
app.use("/floor", floor);
app.use("/head", head);
app.use("/subAccount", subAccount); // this is department
app.use("/department", department); // this is sub_account
app.use("/staff", staff);
app.use("/departmentStructure", departmentStructure);
app.use("/po", po);
app.use("/co", co);
app.use("/feePlan", feePlan);
app.use("/feeInvoiceRecord", feeInvoiceRecord);
app.use("/studentInvoice", studentInvoice);
app.use("/lesson", lesson);
app.use("/notice", notice);
app.use("/examStructure", examStructure);
app.use("/schedule", schedule);
app.use("/leave-policies", leavePolicy);
app.use("/leave-requests", leaveRequest);
app.use("/leave-balance", leaveBalance);
app.use("/examScheduleMapping", examScheduleMapping);
app.use("/libraryStructure", libraryStructure);
app.use("/internalAssessment", internalAssessment);
app.use("/jobSetting", jobSetting);
app.use("/jobs", jobs);
app.use("/grade", grade);
app.use("/credit", credit);
app.use("/evalution", evalution);

app.listen(PORT, () => {
  console.log(`server is running on port ${PORT}`);
});
