export const EVALUATION_PATTERNS = [
  "INTERNAL_EXTERNAL",
  "INTERNAL_ONLY",
  "EXTERNAL_ONLY",
];

export const MANDATORY_COMPONENTS = [
  "THEORY",
  "PRACTICAL",
  "VIVA",
  "PROJECT",
  "INTERNSHIP",
];

export const TIE_BREAKING_METHODS = [
  "HIGHER_CGPA",
  "HIGHER_SGPA",
  "HIGHER_INTERNAL_MARKS",
  "HIGHER_EXTERNAL_MARKS",
  "ALPHABETICAL",
  "RANDOM",
];
